---
title: "Gemma Portion"
author: "Gemma Clark"
date: "Fall 2020"
output: html_document
---
State analyses, milk analyses (Grade A = milk, Grade B = cheese, yogurt, etc.)
(milk fluid, state, milk_facts for the milk stuff, avoid cheese and butter stuff)

# Setup
```{r}
#install.packages('tidytuesdayR')
library(tidytuesdayR)
#install.packages('tidyverse')
library(tidyverse)
#install.packages('ggplot2')
library(ggplot2)
#install.packages('ggpubr')
library(ggpubr)
#install.packages('usmap')
library(usmap)

dairy = tt_load(2019,5)
clean_cheese = dairy$clean_cheese
fluid_milk_sales = dairy$fluid_milk_sales
milk_products_facts = dairy$milk_products_facts
milkcow_facts = dairy$milkcow_facts
state_milk_production = dairy$state_milk_production


```



## Examining Milk Production by State

test

## State Milk Production Across the Decades
```{r}
# Organize states data so that year has columns with milk production
states_by_year = pivot_wider(state_milk_production, names_from = year, values_from = milk_produced)


# Create choropleth figures for milk production at each decade
fig70 = plot_usmap(data = states_by_year, values = '1970', color = 'black' ) +
  scale_fill_continuous(low = 'white', high = 'brown', name = 'Milk Production', label = scales::comma) +
  theme(legend.position = 'right')

fig80 = plot_usmap(data = states_by_year, values = '1980', color = 'black' ) +
  scale_fill_continuous(low = 'white', high = 'brown', name = 'Milk Production', label = scales::comma) +
  theme(legend.position = 'right')

fig90 = plot_usmap(data = states_by_year, values = '1990', color = 'black' ) +
  scale_fill_continuous(low = 'white', high = 'brown', name = 'Milk Production', label = scales::comma) +
  theme(legend.position = 'right')

fig00 = plot_usmap(data = states_by_year, values = '2000', color = 'black' ) +
  scale_fill_continuous(low = 'white', high = 'brown', name = 'Milk Production', label = scales::comma) +
  theme(legend.position = 'right')

fig10 = plot_usmap(data = states_by_year, values = '2010', color = 'black' ) +
  scale_fill_continuous(low = 'white', high = 'brown', name = 'Milk Production', label = scales::comma) +
  theme(legend.position = 'right')

fig17 = plot_usmap(data = states_by_year, values = '2017', color = 'black' ) +
  scale_fill_continuous(low = 'white', high = 'brown', name = 'Milk Production', label = scales::comma) +
  theme(legend.position = 'right')


# Plot the choropleths together
ggarrange(fig70, fig80, fig90, fig00, fig10, fig17, 
          labels = c('1970', '1980', '1990', '2000', '2010', '2017'),
          ncol = 2, nrow = 3)
```



