---
title: "help"
author: "Raina Monaghan"
date: "10/14/2020"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
library(tidytuesdayR)
library(ggplot2)
library(summarytools)
library(rstatix)
library(ggpubr)
library(ggthemes)
library(ggExtra)
  

dairy = tt_load(2019, 5)
```


```{r}
clean_cheese <- dairy$clean_cheese
clean_cheese <- as.data.frame(clean_cheese)

all_cheese <- select(clean_cheese, "Cheddar":"Foods and spreads")
summary_whole <- summarytools::descr(all_cheese, transpose = TRUE)
summary_whole
```

```{r}

sel_vars_totals <-
  select(clean_cheese,
         "Year",
         "Total American Chese":"Total Processed Cheese Products")

sel_vars_total1 <-
  select(clean_cheese,
         "Total American Chese":"Total Processed Cheese Products")

sum_1 <- summarytools::descr(sel_vars_total1)
sum_1 

```


```{r}

total_cheese_consumption = clean_cheese$`Total Natural Cheese` + clean_cheese$`Total Processed Cheese Products`

all_cheese_long <- clean_cheese%>%
  select(Year: "Foods and spreads")%>%
  gather(cheese_type, lbs_per_person, -Year) %>%
  mutate(total_consumption = lbs_per_person/total_cheese_consumption)

ggplot(all_cheese_long, aes(x = Year, y = total_consumption, col = cheese_type)) +
    geom_point(stat = "identity", position = "stack") +
    scale_y_continuous(labels = scales::percent) +
    labs(title = "Total Cheese Consumption by Cheese Type", y = "Percent of Total Consumption")
    
```

```{r}

all_cheese_long %>%
filter(Year < "1979") %>%
  ggplot(aes(x = lbs_per_person, y = cheese_type, fill = cheese_type)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Year) +
  labs(title = "Yearly Cheese Consumption") +
  theme(axis.text.y=element_blank(), axis.text.x=element_blank())

all_cheese_long %>%
filter(Year > "1979" & Year < "1990") %>%
  ggplot(aes(x = lbs_per_person, y = cheese_type, fill = cheese_type)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Year) +
  labs(title = "Yearly Cheese Consumption") +
  theme(axis.text.y=element_blank(), axis.text.x=element_blank())

all_cheese_long %>%
filter(Year > "1989" & Year < "2000") %>%
  ggplot(aes(x = lbs_per_person, y = cheese_type, fill = cheese_type)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Year) +
  labs(title = "Yearly Cheese Consumption") +
  theme(axis.text.y=element_blank(), axis.text.x=element_blank())

all_cheese_long %>%
filter(Year > "1999" & Year < "2010") %>%
  ggplot(aes(x = lbs_per_person, y = cheese_type, fill = cheese_type)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Year) +
  labs(title = "Yearly Cheese Consumption") +
  theme(axis.text.y=element_blank(), axis.text.x=element_blank())

all_cheese_long %>%
filter(Year > "2009") %>%
  ggplot(aes(x = lbs_per_person, y = cheese_type, fill = cheese_type)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Year) +
  labs(title = "Yearly Cheese Consumption") +
  theme(axis.text.y=element_blank(), axis.text.x=element_blank())

```
```{r}

ggplot(clean_cheese) + 
  geom_line(aes(x = clean_cheese$Year,
                 y = clean_cheese$`Total American Chese`,
                  color = "Total American Cheese"),
                size = 2) +
  geom_line(aes(x = clean_cheese$Year, y =
                clean_cheese$`Total Italian Cheese`,
                color = "Total Italian Cheese"),
            size = 2) + 
                labs(
                  title = "Total American and Italian Cheese Consumption",
                  subtitle = "A comparison of pounds consumed per person (1970 to 2017)",
                  y = "lbs per person",
                  x = "Year"
                ) + theme_clean()
```

```{r}

ggplot(clean_cheese) + 
  geom_line(aes(x = clean_cheese$Year,
                 y = clean_cheese$`Total Natural Cheese`,
                  color = "Total Natural Cheese"),
                size = 2) +
  geom_line(aes(x = clean_cheese$Year, y =
                clean_cheese$`Total Processed Cheese Products`,
                color = "Total Processed Cheese"),
            size = 2) + 
                labs(
                  title = "Total Natural Cheese and Total Processed Cheese Consumption",
                  subtitle = "A comparison of pounds consumed per person (1970 to 2017)",
                  y = "lbs per person",
                  x = "Year"
                ) + theme_clean()


```
```{r}
ggplot(clean_cheese,
       aes(x = clean_cheese$Year,
           y = clean_cheese$`Total Processed Cheese Products`,
           color = "Total Processed Cheese")) + geom_point(color = "darkblue") +
  geom_smooth(method = lm,
              se = TRUE,
              fullrange = TRUE, color = "darkred", fill = "lightblue") + 
  labs(title = "Total Processed Cheese Consumption", x = "Year", y = "Consumption (lbs)") + theme_clean()

```
```{r}


```
